version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      # We try to stick to PyQt6 6.7.1 to keep supporting macOS 11
      - dependency-name: "PyQt6"
      - dependency-name: "PyQt6-Qt6"
      - dependency-name: "PyQt6-sip"
    groups:
      python-packages:
        patterns:
          - "*"
